name: assignment11
channels: 
  - conda-forge
  - defaults
dependencies:
  - scikit-image=0.19.2
  - opencv=4.5.5
  - nbconvert=6.4.5
  - python=3.10.2
  - ipython=8.1.1
  - pandas=1.4.1
  - numpy=1.22.2
  - bokeh=3.3.4
  - selenium=4.18.1
  - selenium-manager=4.18.1
  - firefox=123.0
  - geckodriver=0.34.0
